server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lixiaomei-git/config-repo-demo

security:
  basic:
    enabled: true
  user:
    name: user
    password: password
    

      
     